<div class="phone-list contact-list">
    <h1 class="google">Import Google Contacts</h1>
    <div style="text-align: right">
        Phone number: <strong><a href="/web/contacts/list/phoneId/<?php echo $this->phoneId ?>/groupId/<?php echo $this->groupId ?>"><?php echo $this->phoneNumber ?></a></strong>
        | Group: <strong><?php echo $this->groupName ?></strong>
    </div>
    <div style="padding: 5px">
     <?php   if($this->phoneId && $this->groupId) : ?>
          <?php if ($this->loginUrl): ?>
            <strong><?php echo $this->loginUrl; ?></strong>
          <?php endif ?>
    <?php endif ?>
    </div>
    <?php echo $this->message ?>
    <?php if (count($this->contacts)) : ?>
    <form method="post" action="">
        <div style="width: 688px;background: #eee">
            <table border="0" style="width: 666px; text-align: center">
                <thead>
                    <tr>
                        <th style="width: 10%">&nbsp;</th>
                        <th style="width: 20%">Name</th>
                        <th style="width: 30%">Phone number</th>
                        <th style="width: 40%">Email</th>
                    </tr>
                </thead>
        </table>
        </div>
        <div style="height: 444px;width: 688px; overflow: auto; border: 1px solid #eee">
        <table class="tblList" style="width: 666px">
            <?php foreach ($this->contacts as $contact) : ?>
                <tr>
                    <td style="width: 10%">
                        <input type="checkbox" name="contacts[]" value='{"name": "<?php echo $contact['name'] ?>", "phone": "<?php echo $contact['phone'] ?>", "email": "<?php echo $contact['email'] ?>"}' />
                    </td>
                    <td style="text-align: left; width: 20%">
                        <?php echo htmlspecialchars($contact['name']) ?>
                    </td>
                    <td style="width: 30%">
                        <?php echo htmlspecialchars($contact['phone']) ?>
                    </td>
                    <td style="width: 40%">
                        <?php echo htmlspecialchars($contact['email']) ?>
                    </td>
                </tr>

            <?php endforeach; ?>
        </table>
        </div>
        <input type="submit" onclick="return confirm('Are you sure you want to import selected contacts to your contact list (<?php echo $this->groupName ?>) ?')" name="submitContact" value="Import selected contacts" style="font-weight: bold; height: 30px; margin: 10px" />
    </form>
    <?php endif; ?>
</div>
