<script type="text/javascript"    src="http://maps.google.com/maps/api/js?sensor=false"></script>
<script type="text/javascript"   src="/sosdata/audio/audio-player.js" language="JavaScript"></script>
<script type="text/javascript"   src="/scripts/lightbox.js"></script>
<script type="text/javascript"   src="/scripts/jwplayer/jwplayer.js"></script>
<link rel="stylesheet" href="/styles/lightbox.css" type="text/css" media="screen" />

<script type="text/javascript">
var token = '<?php if(isset($this->token)) echo $this->token;?>';
//Load message note
function loadNote() {
	var alertloggroupId = $('#hdAlertloggroupId').val();
	url = "/web/alert/loadnote?alertlogId="+alertloggroupId;
	$('#noteList').load(url);
}

$(document).ready(function(){
    loadNote();
});
</script>

<script type="text/javascript">
//#### Google map
function initialize(el, la,lo) {

      //var latlng2 = new google.maps.LatLng(21.040994081750677, 105.78739643096924);
      var latlng = new google.maps.LatLng(la, lo);
      var myOptions = {
      zoom: 12,
      center: latlng,
      mapTypeId: google.maps.MapTypeId.ROADMAP
    };

    var map = new google.maps.Map(el, myOptions);

    var marker = new google.maps.Marker({
        position: latlng,
        title:"My location"
    });
    // To add the marker to the map, call setMap();
    marker.setMap(map);

}
//Load ajax
$(document).ready(function(){
        $('.google_map_canvas').each(function() {
            var la = $(this).attr("la");
            var lo = $(this).attr("lo");
            if((la != null && lo != null) && (la != 0 && lo != 0) && la != '' && lo != '') { 
                initialize(this, la, lo); 
            } else {
                $(this).parent('.gmap').html('NO LOCATION DATA');
            }
        });

});
//#### Google map //

$(document).ready(function(){
    <?php if ($this->viewType == 'infor') : ?>
    // Load Settings by phoneId
        $('#phone-details-infor').load("/web/phone/settings?layout=off&pid=" + <?php echo $this->phoneId ?>);
    <?php endif ?>
});

</script>

<div class="alert-list">
    <form id="time-display" class="time-display" method="post" action="">
        Enter GMT time:
        <input type="text" id="time_gmt" class="time_gmt" name="time_gmt"
               value="<?php echo $this->time_gmt ?>" size="15" />
        <input type="submit" id="time_submit" class="time_submit" value="Display" />

        <?php echo $this->time_display ?>
        
    </form>
    <form id="search_phone" name="search_phone" method="get" action="">
     <div class="alert-list-select-phone">
         <div class="title"><label class="heading">Enter phone number:</label>
            <input type="text" id="phone_number" class="phone_number" name="phone_number" value="<?php echo $this->phoneNumber ?>" />
            <input type="submit" id="phone_submit" class="phone_submit" value="View" />
            <input type="radio" name="view_type" id="lb_view_history" value="history" <?php if ($this->viewType == 'history') : ?>checked<?php endif ?> /> <label for="lb_view_history">History</label>
            <input type="radio" name="view_type" value="infor" id="lb_view_infor" <?php if ($this->viewType == 'infor') : ?>checked<?php endif ?> /> <label for="lb_view_infor">Phone Information</label>
        </div>
    </div>
    </form>
    <div class="clr">
        <?php echo $this->message ?>
    </div>
    <div id="phone-settings" class="phone-settings"><div id="phone-details-infor" class="setting-list"></div></div>
    <div class="clr"></div>
    <?php if(isset($this->alertDataRows)) : ?>
<!-- COL-LEFT -->
    <div class="col-left">
      <h2 style="text-align: center" class="log-title">MESSAGE CENTER</h2>
       <div class="scroll-alert">
        <div class="note-list" id="noteList"></div>
        <div class="clr"></div>
	<!-- End of recording-list -->

        <?php if(isset($this->alertlogRows) && count($this->alertlogRows) >0) : ?>
        <?php foreach($this->alertlogRows as $row) :?>
            <div class="details">
                <div class="details-title">
                Details
                </div>
                <div>
                <table cellpadding="0" cellspacing="0">
                    <tr>
                        <td>From:</td>
                        <td>
                        <?php echo htmlspecialchars($this->phoneRows->getName()) ?>
                        </td>
                    </tr>
                    <tr>
                        <td>Number:</td>
                        <td><?php if(isset($this->phoneRows)) echo $this->phoneRows->getNumber() ?></td>
                    </tr>
                    <tr>
                        <td>Email:    </td>
                        <td><?php echo htmlspecialchars($this->phoneRows->getEmail()) ?></td>
                    </tr>
                    <tr>
                            <td>Time:    </td>
                            <td><?php echo $row->updated_date ?> GMT</td>
                    </tr>
                    <tr>
                            <td>Latitude:&nbsp;&nbsp;    </td>
                            <td><?php echo $row->latitude ?></td>
                    </tr>
                    <tr>
                        <td>Longitude:&nbsp;&nbsp;  </td>
                            <td><?php echo $row->longtitude ?></td>
                    </tr>
                    <tr>
                            <td>Text:     </td>
                            <td><?php echo htmlspecialchars($row->message) ?></td>
                    </tr>
                </table>
                </div>
        </div>
        <?php endforeach;?>
        <?php endif; ?>
        </div>
    </div>
<!-- END OF COL-LEFT -->

<!-- COL-RIGHT -->
    <div class="col-right">
	<input type="hidden" id="hdAlertloggroupId" value="<?php if(isset($this->alertloggroupId)) echo $this->alertloggroupId?>" />
        <div id="recording-list" class="recording-list">
            <table class="list-alert" cellpadding="0" cellspacing="0">
            <tr>
                    <th>Alert ID</th>
                    <th>Last Updated</th>
                    <th>Status</th>
            </tr>
            <?php if(isset($this->alertlogRowsList)) : ?>
            <?php foreach($this->alertlogRowsList as $row) { ?>
                <?php
                $activeClass =  $row->getToken() == $this->token ? 'active' : '';
                ?>
            <tr class="<?php echo $activeClass ?>">
                <td class="first" >
                        <div class="id-img">
                        <?php if($row->getStatus() == 'Open') : ?><img src="/images/red-circle-ico.png" title="Open"/><?php endif; ?>
                        <?php if($row->getStatus() == 'Connected') : ?><img src="/images/orange-circle-ico.png" title="Open"/><?php endif; ?>
                        <?php if($row->getStatus() == 'Closed') : ?><img src="/images/black-circle-ico.png" title="Closed"/><?php endif; ?>
                        </div>
                        <div class="id-num">
                        <a class="<?php echo $activeClass ?>" href="/admin/index?phone_number=<?php echo $this->phoneNumber ?>&token=<?php echo $row->getToken()?>"><?php echo $row->getId()?></a>
                        </div>
                </td>
                <td class="last">
                        <a class="<?php echo $activeClass ?>" href="/admin/index?phone_number=<?php echo $this->phoneNumber ?>&token=<?php echo $row->getToken()?>">
                                <?php echo $row->getLastUpdated()." GMT"?>
                        </a>
                </td>
                <td>
                        <?php echo $row->getStatus() ?>
                </td>
            </tr>	
            <?php } ?><?php endif; ?>
            </table>
        </div>
        <div class="clr"></div>
        <h2 class="log-title" style="text-align: center">DOWNLOAD CENTER</h2>
        <!-- LOAD LOCATION HERE -->
        <!--div class="location"></div-->
         <div class="alert">
          <div class="scroll-alert">
            <?php if(isset($this->alertDataRows)) :
                $count = 0;
                $maps = $this->maps;
            ?>
            <?php foreach($this->alertDataRows as $key => $rows):
                    ?>
            <div class="alert-rows">

                    <!-- new: display map here -->
                    <!-- GOOGLE MAP -->
                    <?php
                    if (array_key_exists($key, $maps)) :
                        $map = $maps[$key];
                    ?>
                        <div class="gmap">
                            <div class="google_map_canvas" la="<?php echo $map['latitude'] ?>" lo="<?php echo $map['longtitude'] ?>"></div>
                            <div class="date">Created Date: <?php echo $map['updated_date']." GMT" ; ?></div>
                        </div>
                    <?php endif; ?>
                    <!-- GOOGLE MAP -->

                    <!-- MAIN-PHOTO -->
                    <div class="main-photo">
                            <?php foreach ($rows as $row) :?>
                            <?php if($row->type != null && $row->type == 0) :  //image ?>
                            <div class="photo-block">
                                    <div class="photo">
                                            <a href="<?php echo $row->path ?>" rel="lightbox[flowers]" title="Photo by SOSbeacon">
                                                    <img src="<?php echo $row->path ; ?>"/>
                                            </a>
                                    </div>
                                    <div class="date">Created Date: <?php echo $row->created_date." GMT" ; ?></div>
                            </div>
                            <?php endif; ?>
                            <?php endforeach;?>
                     </div>
                     <!-- End of MAIN-PHOTO -->

                     <!-- MAIN-AUDIO -->
                     <div class="main-audio">
                     <?php $audioNum = 0 ; //Number of audio row?>
                     <?php foreach ($rows as $row) :?>
                     <?php if($row->type != 0) : //media ?>
                            <?php $audioNum++ //Up value Number of audio row to 1?>

                            <div class="media">
                                <object id="player" classid="clsid:D27CDB6E-AE6D-11cf-96B8-444553540000" name="player" width="250" height="24">
                                        <param name="movie" value="/scripts/jwplayer/player.swf" />
                                        <param name="allowfullscreen" value="true" />
                                        <param name="allowscriptaccess" value="always" />
                                        <param name="flashvars" value="file=<?php echo $row->path;?>" />
                                        <embed
                                                type="application/x-shockwave-flash"
                                                id="player2"
                                                name="player2"
                                                src="/scripts/jwplayer/player.swf"
                                                width="250"
                                                height="25"
                                                allowscriptaccess="always"
                                                allowfullscreen="true"
                                                flashvars="file=<?php echo $row->path;?>"
                                        />
                                </object>
                            </div>
                            <div class="datetime">Created Date: <?php echo $row->created_date." GMT" ; ?></div>
                    <?php endif; ?>
                    <?php endforeach;?>

                    <!-- When iphone call Emergency, audio null -->
                    <?php $isIphoneCheckin = 0;?>
                    <?php foreach ($rows as $row) :?>
                             <?php if($audioNum == 0 && $row->alertlogType == 1) { //IF Emergency
                                            $isIphoneCheckin = 1;
                                    }
                             ?>
                    <?php endforeach;?>
                     <?php if($isIphoneCheckin == 1) :?>
                            <div class="emergency-null">Emergency calls CAN NOT be recorded on iPhones due to Apple policy</div>
                     <?php endif;?>
                    </div>
                    <!-- END OF MAIN-AUDIO -->
                    <div class="clearFloat"></div>
            </div>
            <?php endforeach;?>
            
            <?php endif;?>
            </div>
          </div>
	</div>
    <div class="clr"></div>
    <?php endif;?>
</div>
<!-- END OF COL-RIGHT -->

