<div class="school-admin">
    <div class="left">
        <a href="/SOSb-School-Examples.pdf" target="_bank" class="big-red-bt sabt1">See how SOSbeacon can be used in your school</a>
        <a href="/web/about/contact" class="big-red-bt sabt2">Contact SOSbeacon to get a school administrator's account</a>
        <a href="http://softwebstudios.com/sosbeacon/login/" target="_bank" class="big-red-bt sabt3">Login to school administrator's emergency contact database</a>
    </div>
    <div class="right">
        <img src="/images/sc1.png" alt="" class="exp" />
        <img src="/images/sc2.png" alt="" class="exp" />
        <img src="/images/sc3.png" alt="" class="exp" />
    </div>
</div>
<style type="text/css">
    a.school-admin {
        display: none;
    }
</style>