  <!-- Container -->
    <div id="Container">
         <div id="ContainerInside">
          <div id="Content">
                <div class="main-content">
                       <div class="login-home">
      
        
        <div class="login-panel">
		         

       <div>Password has been reset, please check your email @ <?=$form_r[email]?></div>                
        </div>
</div>                </div>               
           </div>
          <? include($_CFG['fragmentsDir'].$_SESSION[culture].'/fragment_footer.inc');?>
         </div>   
     </div>
     <!-- /Container -->
     
