<div class="nav">
<ul class="ul-nav">
	<li id="dashboard">
		<a href="/admin/index">Dashboard</a>
	</li>
	<li id="customers">
		<a href="/admin/user/index">User</a>
	</li>
        <li id="send-email">
		<a href="/admin/user/send-email">Send Email</a>
	</li>
	<li id="smslog">
		<a href="/admin/phone/smslog">Sms Log</a>
	</li>
	<li id="emaillog">
		<a href="/admin/phone/emaillog">Email Log</a>
	</li>
        <li id="errorlog">
		<a href="/admin/log">Error Log</a>
	</li>
</ul>
</div>