<script type="text/javascript">
    function resetForm() {
        $('#editForm').slideUp();
        $('#editForm').remove();
        $('.contact-name .view').show();
    }
    $(document).ready(function() {
        jQuery.validator.addMethod('phoneUS', function(number, element) {
            number = number.replace(/\s+/g, "");
            return this.optional(element) || (number.indexOf('84') == 0) || number.length > 9 && number.match(/^(1-?)?(\([2-9]\d{2}\)|[2-9]\d{2})-?[2-9]\d{2}-?\d{4}$/);
        }, 'Please specify a valid US phone number');

        jQuery.validator.addMethod('requireEmailOrPhone', function(value, element) {
            return ($.trim($('#editEmail').val()) != '') || ($.trim($('#editTextPhone').val()) != '');
        }, 'Please enter email or phone number');
        
        var contactForm = '<div id="editForm" class="editForm" style="display:none"><table>' +
                        '<tr><td>Name:</td><td><input type="text" id="editName" name="editName" class="required" size="20" /></td></tr>' +
                        '<tr><td>Email:</td><td><input type="text" id="editEmail" name="editEmail" class="email requireEmailOrPhone" size="20" /></td></tr>' +
                        '<tr><td>Text phone:</td><td><input type="text" id="editTextPhone" name="editTextPhone" class="requireEmailOrPhone phoneUS" size="20" /></td></tr>' +
                        '<tr><td>Voice phone:</td><td><input type="text" id="editVoicePhone" name="editVoicePhone" class="phoneUS" size="20" /></td></tr>' +
                        '</table><input type="hidden" id="editId" name="editId" />' +
                        '<input type="submit" id="editSubmit" value="Save" />' +
                        '<input type="button" id="cancel" value="Cancel" />' +
                        '</div>';
        $('a.add').click(function() {
            resetForm();
            $('#addForm').html(contactForm);
            $('#editForm').slideDown();
        });
        $('a.view').click(function() {
            resetForm();
            $(this).parents('tr').find('.edit-form').html(contactForm);
            $('#editForm').slideDown();
            $(this).parents('tr').find('.contact-name .view').hide();
            $('#editName').val($(this).parents('tr').find('.contact-name-value').text());
            $('#editEmail').val($(this).parents('tr').find('.contact-email-value').text());
            $('#editTextPhone').val($(this).parents('tr').find('.contact-textphone-value').text());
            $('#editVoicePhone').val($(this).parents('tr').find('.contact-voicephone-value').text());
            $('#editId').val($(this).parents('tr').find('.contact-id-value').text());
            var type = parseInt($(this).parents('tr').find('.contact-type-value').text());
            var allowEdit = parseInt($(this).parents('tr').find('.contact-allow-edit').text());
            if (allowEdit == 1) {
                $('#editSubmit').click(function() {
                    var groupId = $(this).parents('tr').find('.contact-groupid-value').text();
                    var groupName = $(this).parents('table').find('tr.contacts-group-' + groupId + '.default-contact .contact-name-value').text();
                    groupName = groupName.substring(groupName.indexOf('Neighborhood'));
                    alert('You cannot modify contacts in the "' + groupName + '" group; see your group manager.');
                    return false;
                });
            } else if (type == 1) {
                $('#editForm table input').attr('disabled', 'disabled');
                $('#editSubmit').attr('disabled', 'disabled');
            }
        });
        $('#cancel').live('click', function() {
            resetForm();
        });
        $('a.delete').click(function() {
            if(confirm('Are you sure you want to delete this contact?')) {
                resetForm();
                $('#deleteId').val($(this).parents('tr').find('.contact-id-value').text());
                setLoading();
                $('form').submit();
            }
        });
        $('#editSubmit').live('click', function() {
            if ($('form').isValid()) {
                setLoading();
            }
        });
        if ($('a.bt-unjoin').length > 0) {
            $('a.bt-unjoin').click(function() {
                if(confirm('Are you sure you want to unjoin current group?')) {
                    resetForm();
                    $('#doUnjoin').val(1);
                    setLoading();
                    $('form').submit();
                }
            });
        }
        $('form').validate();
    });
</script>
<div class="message"><?php echo $this->message ?></div>
<form method="post" action="" class="contact-form list">
    <label class="import-label"><a href="/webapp/groups">&lsaquo;&lsaquo; Back</a>  Import:</label>
    <a class="icon-button add">New</a>
    <?php if ($this->allowJoinGroup): ?>
        <?php if (count($this->joinContacts)) : ?>    
            <a class="icon-button join bt-unjoin" href="#">Unjoin</a>
        <?php else: ?>
            <a class="icon-button join" href="/webapp/groups/join/groupId/<?php echo $this->groupId ?>">Join</a>
        <?php endif; ?>
    <?php endif; ?>
    <a class="icon-button import-yahoo" href="/webapp/groups/yahoo-contacts/groupId/<?php echo $this->groupId ?>/back/webapp">Yahoo</a>
    <a class="icon-button import-google" href="/webapp/groups/google-contacts/groupId/<?php echo $this->groupId ?>/back/webapp">Google</a>
    <div class="clr"></div>
    <input type="hidden" id="deleteId" name="deleteId" />
    <input type="hidden" id="doUnjoin" name="doUnjoin" />
    <div id="addForm" class="edit-form"></div>
    <table class="grid" cellpadding="0" cellspacing="0"> 
    <?php $count = 0; foreach ($this->contacts as $c): $count++; $type = intval($c->getType()) ?>
        <tr id="contact-<?php echo $c->getId(); ?>" class="contacts-group-<?php echo $c->getGroupId();echo $c->getType() == 1 ? ' default-contact ' : ''; ?>">
            <td class="contact-name">
                <a class="view" title="View / edit contacts" href="#contact-<?php echo $c->getId() ?>">
                    <span class="contact-groupid-value" style="display: none"><?php echo $c->getGroupId(); ?></span>
                    <span class="contact-id-value" style="display: none"><?php echo $c->getId() ?></span>
                    <span class="contact-type-value" style="display: none"><?php echo $c->getType() ?></span>
                    <span class="contact-voicephone-value" style="display: none"><?php echo $c->getVoicePhone() ?></span>
                    <span class="contact-name-value"><?php echo htmlspecialchars($c->getName()) ?></span>
                    <span class="contact-textphone-value"><?php echo $c->getTextPhone() ?></span>
                    <span class="contact-email-value"><?php echo $c->getEmail() ?></span>
                    <span class="contact-allow-edit" style="display: none">
                        <?php if ($this->groupId != $c->getGroupId()): ?>1<?php else : ?>0<?php endif ?>
                    </span>
                </a>
                <div class="edit-form"></div>
            </td>
            <td class="delete">
            <?php if ($type == 0 && ($this->groupId == $c->getGroupId())): ?>
                <a title="Delete" class="delete" href="#contact-<?php echo $c->getId() ?>">Delete</a>
            <?php endif ?></td>
        </tr>
    <?php endforeach; ?>
    </table>
</form>