<script type="text/javascript">
<!--
//Check valid email
function IsValidEmail(email) {
	var filter = /^([\w-\.]+)@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.)|(([\w-]+\.)+))([a-zA-Z]{2,4}|[0-9]{1,3})(\]?)$/;
	
	return filter.test(email);
}

function setReadonly(status) {
	if (status == null)
		status = false;
	
	document.getElementById('name').readOnly = status;
	document.getElementById('email').readOnly = status;
	document.getElementById('subject').readOnly = status;
	document.getElementById('message').readOnly = status;
	document.getElementById('submit').disabled = status;
}

function clearForm() {
	$('#name').val('');
	$('#email').val('');
	$('#subject').val('');
	$('#message').val('');
}


$().ready(function() {
	$('#submit').click(function(){
		if($('#name').val() == '') {
			alert('Name field cannot be null !');
			$('#name').focus();
		}
		else if($('#email').val() == '') {
			alert('Email field cannot be null !');
			$('#email').focus();
		}
		else if(!IsValidEmail($('#email').val())) {
			alert('Email field is not valid - example@domain.com !');
			$('#email').focus();
		}
		else if($('#subject').val() == '') {
			alert('Subject field cannot be null !');
			$('#subject').focus();
		}
		else if($('#message').val() == '') {
			alert('Message field cannot be null !');
			$('#message').focus();
		}
		else { 
			var url = '/web/about/sendmail?name='+$('#name').val()+'&email='+$('#email').val();
			url += '&subject='+$('#subject').val()+'&message='+$('#message').val();

			//Show loader icon
			$('.loader').show();
			//Unable input form
			setReadonly(true);
			
			$.post(url, function(data){
				if (data == 'false') {
					$('#flag').html('Email sending failed');
				} 
				else if (data == 'true'){
					$('#flag').html('Email sent successfully to our mail server.');
				}
				//Hide loader icon
				$('.loader').hide();
				//Clear form when send mail successfull
				clearForm();
				//Available input form
				setReadonly(false);
			}); //End of post ajax
		}//End of else
	});
});

//-->
</script>

<div class="contact-index contactForm">
<h2>Contact</h2>		
<div class="div1">
	<div class="left">
		<form id="frm" action="/web/about/sendmail" method="post">
			<label class="name" for="name">Name:</label><br />
			<input type="text" name="name" id="name" class="text" value="" />
                        <br />
			<label class="email" for="email">Email:</label><br />
			<input type="text" name="email" id="email" class="text" value="" />
                        <br />
			<label class="subject" for="subject">Subject:</label><br />
			<input type="text" name="subject" id="subject" class="text" value="" />
                        <br />
			<label class="message" for="message">Message:</label><br />
			<textarea name="message" rows="5" cols="40" id="message" class="textarea"></textarea>
                        <br />
			<input type="button" name="submit" id="submit" class="submit" value="Send..." />
	
			<p class="loader">
				<img src="/images/ajax_spinner.gif" alt="Loading..." />
			</p>
			<div class="flag" id="flag"></div>
		</form>
	</div><!-- .left /end -->	
	<div class="right">
		<p>You can contact us using the form to your left, alternatively you can use any of the links below:</p>
		<ul>
		  <!-- <li class="telephone">877-426-2223</li> -->

		  <!-- <li class="email"><a href="mailto:hello@joe-macdonald.co.uk">noreply@sosbeacon.org</a></li>-->
		  <li class="skype">sosbeacon.org</li>
		  <!-- <li class="twitter"><a href="http://www.twitter.com/josephmacdonald">twitter.com/sosbeacon.org</a></li>-->
		</ul>
	</div><!-- .right /end -->
	<div class="clearFloat"></div>
</div>
</div>