<div class="features-index">
<div class="div1-1">
<h2>SOSbeacon FEATURES</h2><br/>
<h2><img src="/images/pdf-download.gif"> <a href="/SOSbeacon-Features.pdf" > PDF Download</a></h2><br/>

<strong>EMERGENCY CALLS</strong>:  When you call 911 from SOSbeacon, the mobile phone software sends your family
 and friends an alert that you called 911, and provides a link that shows your location. 
 On some phones,  SOSbeacon provides an audio recording of your 911 call so your help community
  knows more specifically what your problem is.  If you have opted in, SOSbeacon also notifies good 
  Samaritans in your neighborhood that an SOSbeacon member is in distress and they have the option
   to be early responders.<br/><br/>

<strong>PERSONAL SECURITY THREATS AND OTHER DISTRESS SITUATIONS</strong>:  SOSbeacon lets you record images 
and audio from distress situations (eg auto accidents, medical problems)  and alert your help community with 
links to your location, your recorded images and audio, that you may need help.<br/><br/>

<strong>CHECKING IN</strong>: Why worry friends and family needlessly?  SOSbeacon's checking in function lets you check in 
with friends and family showing your location and a message (default: I'm OK)<br/><br/><br/>



<strong>FEATURES PLANNED FOR FUTURE RELEASES</strong><br/><br/>

<strong>REMOTE CONTROL</strong>: Monitor an SOSbeacon phone you control to act as a remote security camera or two way
 walkie-talkie.  Locate lost phones (select smartphones only).<br/><br/>

<strong>INCOMING GOVERNMENT ALERTS</strong>: Sets incoming alerts preferences on your phone's website.  
Alerts can be sent TO a phone based on its location (e.g. emergency weather alert, tsunami, 
wild-fire evacuation alert, earthquake, etc). <br/><br/>

<strong>ARE YOU OK?</strong>:  This is experimental software that uses the phone's accelerometer to detect a fall or crash, 
similar to the way a car airbag is triggered.  If the user does NOT respond to the audio question: Are you OK? 
with either audio OK or by pushing the OK button, the first level alert is activated.   
In theory, with this app, one could purposely activate an alert by flinging her phone against a wall or floor.  
We will hold a contest for the best versions of this application.

</div>
</div>