<div class="about-index">
    <p>
        <strong>About SOSbeacon.org</strong><br />
        SOSbeacon.org is a non-profit organization that provides mobile phone and Internet services dedicated to saving lives, helping those in distress, reducing first response time and minimizing the anxiety of emergencies.
    </p>
    <p>
        <strong>SOSbeacon for Families:</strong><br />
        SOSbeacon makes you and your community more secure. Are you in distress?… Alert your community with data they can use to get you help. Are you available to help a neighbor in distress? … Set your phone’s Good Samaritan status to "on-line". By documenting details of an incident using its smartphone "eye-witness" recordings, SOSbeacon instantly provides information and collaborative communications to improve emergency response. SOSbeacon effectively mobilizes your community when you need it the most. 
    </p>
    <p style="text-align: center; "><br />
        <span style="font-size: 26px; ">SOSbeacon leverages the safety in numbers</span><br />
        50% of the world’s population, approximately 3.3 billion people, have mobile phones. <br />
        In the United States the number of mobile phones equals 91% of the population.<br />
        Mobile industry research firm Informa Telecoms & Media report<br /><br /><br />
    </p>
    <p>
        <strong>Note from Cliff Orloff, founder</strong><br />
        We have the technology to be safer and more secure. Bringing emergency services and your help community together using modern communications technology in times of need is better than relying just on government services alone. Use SOSbeacon to be better prepared.
    </p>
</div>