<div class="privacy-privacy">
<div class="privacy-content">
<h2>SOSbeacon Privacy Policy</h2><br/>

Your privacy is important to SOSbeacon, and we are committed to maintaining the security of your personal information.
SOSbeacon makes the SOSbeacon service and related software available through the SOSbeacon website located at
www.SOSbeacon.org (the “Site”). Such service, software and Site are collectively referred to as the “SOSbeacon
SERVICE”. SOSbeacon is pleased to provide this Privacy Policy to inform you of our practices with respect to how we
collect and use personally identifiable information through the SOSbeacon SERVICE. Part of simplifying and enhancing
mobile phone experiences involves enabling users to share those experiences with the people that are most important to
them — wherever they are. We understand that everything might not be suitable for sharing, so we give users control over
what gets shared as well as who can see it.<br/><br/>

<strong>What We Collect</strong>: The data that we regularly collect about visitors to the Site (e.g., IP address, browser type, pages
accessed, duration of visit, etc.) does not necessarily enable us to personally identify you, and that is not our intention. We
do collect personally identifiable information about you, such as your name and phone number, but only if you voluntarily
provide it by registering with us for using the SOSbeacon SERVICE.<br/>
<strong>Automated-Collection Information</strong>: To facilitate your use of the SOSbeacon SERVICE, SOSbeacon may automatically
collect certain types of information when you access or use the SOSbeacon SERVICE. For example, in order to provide
you with the SOSbeacon SERVICE, we may collect information about your mobile device (e.g., phone number, type,
serial number, operating systems), the version of the SOSbeacon mobile software you are using (e.g., type and version),
and about your use of the SOSbeacon SERVICE (e.g., time-stamped log of data exchanges). In order to collect this data,
SOSbeacon may utilize software and other automated tools and files such as “cookies.” These automated tools and files
may reside on our servers or on your computer or device. If you disable our ability to use automated tools and files, your
ability to access and use all or part of the SOSbeacon SERVICE may be limited or disabled completely.<br/>
<trong>Use of Information</strong>: SOSbeacon uses your personally identifiable information primarily to provide you with the
SOSbeacon SERVICE and to provide customized content on the SOSbeacon SERVICE that is of interest to you and that
you may make available to others via you sending alerts with links to your data. The information is also used to verify your
authority to access the SOSbeacon SERVICE and to contact you when reasonably necessary. SOSbeacon may also use
any information you have provided as reasonably necessary to administer or provide customer support for the
SOSbeacon SERVICE.<br/>
<strong>Disclosure</strong>: SOSbeacon will disclose your personally identifiable information if we believe it is necessary to do so in order
to comply with law, regulation or other governmental authority or to prevent harm to yourself or others.<br/>
<strong>Security</strong>: In the event that you place an payment through the SOSbeacon SERVICE, your credit card information will be
encrypted using SSL technology before being transmitted over the internet. Because any other personally identifiable
information you submit to SOSbeacon is purely voluntary and should not be of a particularly sensitive nature, we employ
our standard security measures with respect to this information and do not use special encryption methods at this time.
SOSbeacon user accounts are secured by user-created passwords and HTTPs when signing in. Please note that
SOSbeacon cannot guarantee the security of user account information. Unauthorized entry or use, hardware or software
failure, and other factors may compromise the security of user information at any time.<br/>
<strong>Policy Changes</strong>: SOSbeacon reserves the right to change this privacy policy, and will post any revisions on the Site. We
encourage you to review this Privacy Policy regularly for any changes. Your continued use of the Site will be subject to the
then-current privacy policy.<br/>
<strong>International Visitors and Customers</strong>: The Site is hosted in the United States. If you are visiting from the European
Union (EU) or other regions with laws governing data collection and use that may differ from U.S. law, please note that
you are transferring your personal data to the United States which does not have the same data protection laws as the EU
and by providing your personal data you consent to: (a) The use of your personal data for the purposes identified above in
accordance with this Privacy Policy; and (b) The transfer of your personal data to the United States as indicated above.<br/>
<strong>No Error-Free Performance</strong>: SOSbeacon does not guarantee error-free performance under this Privacy Policy. We may
not always catch an unintended privacy issue, despite our efforts to do so. Accordingly, we welcome your feedback
regarding any privacy concerns that you may have, including how we can improve this Privacy Policy. We will use
reasonable efforts to comply with this Privacy Policy and will take prompt corrective action when we learn of any failure to
comply with it.<br/>
<strong>Legal Notices</strong>: This Privacy Policy is subject to the terms in our Terms of Service, available for review at
http://www.SOSbeacon.org/terms, including terms regarding limitations on damages, disclaimers of warranties, and
resolution of disputes. Our Terms of Service take precedence over any conflicting provision in this Privacy Policy. This
Privacy Policy is governed by the laws of the State of California, excluding any conflicts of law principles.<br/>
<strong>Questions</strong>: If you have any questions about our privacy practices, please feel free to contact us at:
privacy@SOSbeacon.org
</div>
</div>
