
<div style="font-size:32px; padding: 50px 20px 0">Coming Soon</div>
  <!-- iframe width="420" height="315" src="http://www.youtube.com/embed/njI2Xcr-jUM" frameborder="0" allowfullscreen></iframe-->
  
  <!-- div class="footer-copyright" style="font-size:11px">Copyright &copy; 2010 SOSbeacon. All Rights Reserved - 
    <a href="/web/about/terms">Terms of service</a> - 
    <a href="/web/about/privacy">Privacy</a>
  </div-->
  
