<div class="terms-terms">
<div class="terms-content">
<h2>SOSbeacon Terms of SERVICE</h2><br/>
Welcome to the SOSbeacon service! SOSbeacon provides its service and related software (collectively, the “SERVICE”) subject to these Terms of
SERVICE. <strong>IMPORTANT—READ CAREFULLY: PLEASE READ THE FOLLOWING TERMS CAREFULLY BEFORE ACCESSING THE SERVICE VIA
THE WEB OR MOBILE PHONE. THESE TERMS OF SERVICE (THIS “AGREEMENT”) ARE A LEGAL AND BINDING AGREEMENT BETWEEN
YOU AND SOSbeacon Inc. (“SOSbeacon” or "SERVICE"). BY COMPLETING THE SOSbeacon REGISTRATION PROCESS OR OTHERWISE
ACCESSING OR POSTING CONTENT ON THE SERVICE, YOU AGREE TO BE BOUND BY ALL OF THE TERMS AND CONDITIONS OF THIS
AGREEMENT. IF YOU DO NOT AGREE TO ALL OF THE TERMS OF THIS AGREEMENT, DO NOT CLICK ON THE BUTTON BELOW ACCEPTING
THIS AGREEMENT AND DO NOT USE THE SERVICE.</strong> You are solely responsible for any charges that you incur with your wireless carrier in
connection with your use of the SERVICE.<br/><br/>

<strong>DATA USAGE:</strong> YOUR USE OF THE SERVICE INVOLVES THE TRANSMISSION OF DATA TO AND FROM YOUR MOBILE PHONE, WHICH MAY BE
SUBJECT TO CARRIER DATA CHARGES. FOR THIS REASON SOSBEACON STRONGLY RECOMMENDS THAT YOU OBTAIN AN UNLIMITED
DATA PLAN FROM YOUR WIRELESS SERVICE PROVIDER. REVIEW YOUR WIRELESS PLAN OR CONTACT OR CARRIER ABOUT PRICING
BEFORE USING THE SERVICE. SOSBEACON WILL NOT BE RESPONSIBLE FOR ANY DATA CHARGES INCURRED IN CONNECTION WITH THE
SERVICE.<br/>
<strong>BETA VERSION</strong>: You understand that the SERVICE is still in the Beta stage of development and may contain errors, bugs and other problems that
could cause system failures. The testing and quality assurances of the SERVICE have not yet been completed and use of the SERVICE and the
SERVICE content is at your sole risk. Furthermore, wireless communications are inherently unreliable in some locations and certain situations which
may prevent SOSbeacon from operating as expected.<br/>
<strong>MODIFICATIONS</strong>: SOSbeacon reserves the right, at is sole discretion, to change, modify, add or remove portions of this Agreement at any time. When
this Agreement is modified, SOSbeacon will revise the “Last Updated” date above. It is your responsibility to check the terms in this Agreement
periodically for changes. Your continued use of the SERVICE following the posting of changes to the Agreement will be subject to the then current
Terms of SERVICE, which shall supersede all earlier versions.<br/>
<strong>ACCESS TO THE SERVICE; MODIFICATIONS TO SERVICE</strong>: SOSbeacon does not provide you with the equipment to access the SERVICE or use
the Software. You are responsible for all fees charged by third parties to access the SERVICE (e.g., data charges by wireless carriers). SOSbeacon
reserves the right to modify or discontinue, temporarily or permanently, all or part of the SERVICE without notice. We will not be liable to you or any third
party for any modification, suspension, or discontinuance of the SERVICE.
License to Software. Subject to the terms of this Agreement, SOSbeacon will grant to you a limited, personal, non-exclusive, non-transferable license to
use one copy of the SOSbeacon software provided to you by SOSbeacon (the “Software”) to create one account on a single wireless device solely to
access the SERVICE to the extent you have the right to access the SERVICE. Your right to access the SERVICE will be limited by the terms of this
Agreement. Except for this license granted to you, the company powering the SOSbeacon service on behalf of SOSbeacon, SOSbeacon, Inc.
(“SOSbeacon”) retains all right, title, and interest in and to the Software, including all related intellectual property rights. The Software is protected by
applicable intellectual property laws, including United States copyright law and international treaties. Except as otherwise explicitly provided in this
Agreement or as may be expressly permitted by applicable law, you will not, and will not permit or authorize third parties to: (a) reproduce, modify,
translate, enhance, decompile, disassemble, reverse engineer, or create derivative works of the Software; (b) rent, lease, or sublicense the Software;
nor (c) circumvent or disable any security or technological features or measures in the Software.<br/>
<strong>PRIVACY POLICY</strong>: Your use of the SERVICE is governed by the SOSbeacon Privacy Policy, which is available at <a href="http://www.SOSbeacon.org/privacy">http://www.SOSbeacon.org/privacy</a> and incorporated by reference into these terms.<br/>
<strong>CONTENT</strong>: You acknowledge that you are responsible for the information and material that you (or your representatives) submit to the SERVICE or
transmit through the SERVICE (your “Content”), and that you, and not SOSbeacon, will have full responsibility for each of your Content, including its
legality, reliability, appropriateness, and originality. Unless otherwise expressly stated in this Agreement or in the SOSbeacon Privacy Policy, you agree
that any Submission provided by you in connection with your use of the SERVICE is provided on a non-proprietary and non-confidential basis. You will
retain all ownership rights in Content that you create and upload to SOSbeacon. When you submit Content to SOSbeacon, in order to allow us to deliver
our service, you hereby grant to SOSbeacon, a non-exclusive, royalty-free, worldwide license to use, copy, modify, sublicense, and distribute your
Content on and through the SERVICE (e.g., resizing your images, organizing into recording sessions, or sharing with friends/family). Content that is part
of your private profile (e.g., your recorded data, calls, SMS messages) are subject to the SOSbeacon Privacy Policy and will not be distributed to third
parties unless directed by you (e.g., thru making your content accessible to friends or visitors to SOSbeacon, or via sms alerts) or as otherwise
described in the SOSbeacon Privacy Policy. You represent and warrant that: (i) you own all right title and interest in your Content or otherwise have the
right to grant the license set forth herein, and (ii) the posting of your Content on or thru the service does not (and will not) violate the privacy rights,
publicity rights, copyrights, contract rights or any other rights of any person. You agree to pay all royalties, license fees and any other monies owning any
person by reason of any Content posted by you on or thru the SERVICE. You will be solely liable for any damage resulting from any infringement of
copyrights, trademarks, or other proprietary rights or any other harm resulting from any Content. SOSbeacon does not actively monitor your postings to
the SERVICE. However, in our efforts to promote good citizenship within the SOSbeacon community, if SOSbeacon becomes aware of inappropriate
use of the SERVICE, SOSbeacon may respond in any way that SOSbeacon deems appropriate in its sole discretion. You acknowledge that SOSbeacon
may report to law enforcement authorities any actions that may be considered illegal, as well as any reports it receives of such conduct. When
requested, SOSbeacon may cooperate with law enforcement agencies in any investigation of alleged illegal activity. SOSbeacon may remove any
Submission that SOSbeacon determines, in its sole discretion, violates the terms of this Agreement or are otherwise deemed by SOSbeacon to be
inappropriate for posting.<br/>
<strong>SYSTEM USE POLICIES</strong>: SOSbeacon asks that you respect our on-line community and participating individuals. Your conduct should be guided by
common sense and basic etiquette. To further these common goals when posting Content to or otherwise using the SERVICE, you agree not to: Use
SOSbeacon facilities, services or resources (including the SERVICE) in a manner which violates any applicable laws or regulations; Intentionally seek
information on, obtain copies of or modify files, other data or passwords belonging to other users without permission; solicit a member’s password or
other account information; or harvest user names, email addresses or other personal information for any purpose; Defame, abuse, harass, stalk,
threaten, or otherwise violate the legal rights (such as rights of privacy and publicity) of others; use racially, ethnically, or otherwise offensive language
including attacks on sex or sexual orientation; or discuss or incite illegal activity; or use explicit/obscene language or solicit/post sexually explicit images
(actual or simulated); Post Content that contain nudity, violence, or offensive subject matter; Promote information that you know to be false or misleading
or that promotes or facilitates illegal activities, piracy, or conduct that is abusive, threatening, obscene, defamatory or libelous; Use the SERVICE in
furtherance of commercial activities; Sell or otherwise transfer your profile or account on the SERVICE; or Use SOSbeacon facilities, services or
resources in a manner that interferes with or disrupts other network users, services or equipment. Such interference or disruption includes, but is not
limited to: (i) propagation of computer worms or viruses, (ii) use of the network to make unauthorized entry to other computational, information or
communications devices or resources, or (iii) use of automated processes to interact with the SERVICE, such as scripts to add friends or harvest data.
This includes unauthorized security probing activities or other attempts to evaluate the security integrity of a network or host system without permission.
SOSbeacon reserves the right to investigate and take legal action against anyone who, in SOSbeacon’s sole discretion, violates the restrictions set forth
in this Agreement, including without limitation removing any offending profile information or Content, and terminating your access to the SERVICE.<br/>
<strong>CONTENT</strong>: You agree that your SOSbeacon uploaded Content (or other Content) will not include any photographs containing nudity, or obscene, lewd,
violent, harassing, sexually explicit or otherwise objectionable subject matter. Notwithstanding the foregoing, you acknowledge that SOSbeacon does
not, and can not, actively monitor content, and therefore you may be exposed to inaccurate, inappropriate, offensive or sexually explicit material posted
by other users to the SERVICE, and SOSbeacon assumes no responsibility or liability for this material.<br/>
<strong>USE OF COPYRIGHTED MATERIALS/TRADEMARKS</strong>: Any materials on the SERVICE that are provided by SOSbeacon or its licensors, including
without limitation any documentation, content, text, data, graphics, images, interfaces or other materials or works of authorship, (the “Materials”) are
copyrighted materials owned by or licensed to SOSbeacon. All rights are reserved. The Materials contain trademarks, service marks and trade names
which are owned by SOSbeacon and its affiliates, and may also contain brand and product names which are trademarks, service marks or trade names
of third parties which are owned by their respective owners. Except as otherwise noted in the SERVICE, you are hereby authorized to view, download,
cache, copy and print the Materials (exclusive of software code) solely for personal use and not for resale or further distribution, subject to the following
conditions: Any copy of the Materials or portion thereof must include the SOSbeacon copyright notice. SOSbeacon reserves the right to revoke such
authorization at any time, and any such use by you shall be discontinued immediately upon notice from SOSbeacon. Nothing contained in the SERVICE
shall be construed as conferring any license or right under any copyright, trade secret, patent, trademark or other intellectual property rights (“IP Rights”)
of SOSbeacon, its affiliates, or any third party, and, except as expressly provided in this Agreement all such IP Rights in the Materials and the SERVICE
are expressly reserved to SOSbeacon, its affiliates, and any third party, as applicable. Notices of Copyright Infringement. SOSbeacon respects the
intellectual property rights of others, and asks you to do the same. It is the policy of SOSbeacon to terminate the access privileges of those who
repeatedly infringe the copyright rights of others. If you believe that your work has been posted on the SERVICE in a way that constitutes copyright
infringement, please contact SOSbeacon at the address below and provide the following information: (1) an electronic or physical signature of the
person authorized to act on behalf of the owner of the copyright interest; (2) a description of the copyrighted work that you claim has been infringed, and
identification of the URL or other specific location on the SERVICE where the material that you claim is infringing is located; (3) your address, telephone
number, and email address; (4) a statement by you that you have a good faith belief that the disputed use is not authorized by the copyright owner, its
agent, or the law; and (5) a statement by you, made under penalty of perjury, that the above information in your notice is accurate and that you are the
copyright owner or authorized to act on the copyright owner’s behalf.
SOSbeacon’s designated agent for notice of copyright infringement can be reached at:
SOSbeacon Inc. Attention: Copyright Compliance Officer
5953 Riverside Blvd - Business Office
Sacramento, CA 95831 USA
[Email:] content@SOSbeacon.org<br/>
<strong>RESTRICTIONS ON USE</strong>: You agree that you will only use the SERVICE for personal use and not in connection with any commercial endeavors,
including without limitation, advertisements, affiliate links, and other forms of solicitation, the posting of which may be removed from your recordings
without notice and may result in termination of your access to the SERVICE.<br/>
<strong>PASSWORD RESTRICTED AREAS OF THE SERVICE</strong>: Certain areas of the SERVICE may be password restricted to registered users (“Password-
Protected Areas”). If you have registered as an authorized user to gain access to these Password-Protected Areas, you agree that you are entirely
responsible for maintaining the confidentiality of your password, and agree to notify SOSbeacon if the password is lost, stolen, disclosed to an
unauthorized third party, or otherwise may have been compromised. You agree that you are entirely responsible for any and all activities that occur
under your account, including any fees that may be incurred under your password-protected account, whether or not you are the individual who
undertakes such activities. You agree to immediately notify SOSbeacon of any unauthorized use of your account or any other breach of security in
relation to your password or the SERVICE that is known to you by contacting content@SOSbeacon.org.<br/>
<strong>DISCLAIMER OF WARRANTIES</strong>: Your use of the service is at your sole risk. the service is provided on an “as is” and “as available” basis. SOSbeacon
makes no, and hereby disclaims all warranties, express, implied and statutory, including without limitation, the implied warranties of merchantability,
fitness for a particular purpose, title, non-infringement of third party rights, compliance with Federal, State and local regulations, the accuracy, timeliness,
relevance or completeness of the SERVICE or any other warranties regarding the SERVICE, content, or the quality, suitability or truth of any content
contained on the SERVICE or included as part of the SERVICE. You acknowledge and agree that SOSbeacon does not warrant that access to the
SERVICE will be uninterrupted or error-free. SOSbeacon specifically denies any responsibility for the accuracy or quality of information obtained through
our SERVICE. any material uploaded or downloaded or otherwise obtained through the use of the SERVICE is done at your own discretion and risk and
you will be solely responsible for any damage to your equipment or DEVICE, loss of data, or DATA OR SERVICE CHARGES that result from the
download of any material through the service.<br/>
<strong>LIMITATION OF LIABILITY</strong>: You agree that SOSbeacon shall not be liable to you or any third party claiming through you for any damages in connection
with your inability to use the service or any content appearing on the SERVICE. In no event will SOSbeacon be liable to you or any third party claiming
through you for any direct, indirect, consequential, exemplary, punitive, special or incidental damages, including without limitation, damages arising from
claims related to personal injury or death, loss of data, lost revenue, lost profits, loss of use or other economic advantage, change in applicable
government regulations, regardless of the form of the action and regardless of whether SOSbeacon has been advised of the possibility of such
damages. Notwithstanding the foregoing limitations, in no event will the total, cumulative liability of SOSbeacon for damages under this Agreement
exceed the amounts paid by you to SOSbeacon, if any, for the SERVICE during the six months immediatly preceeding the event giving rise to such
damages.<br/>
<strong>TERMINATION</strong>: If you violate this Agreement, SOSbeacon reserves the right to terminate service to you without notice. You understand that
SOSbeacon has the right to terminate any account for any reason that SOSbeacon interprets as abuse of the service.
Indemnification. You agree to defend, indemnify and hold harmless SOSbeacon, its affiliates, officers, directors, employees and agents, from and
against any and all claims, damages, obligations, losses, liabilities, costs of debt, and expenses (including but not limited to attorneys’ fees) arising from:
(i) your use of and access to the SERVICE; (ii) your violation of any term of this Agreement; (iii) your violation of any third party right, including without
limitation any copyright, property, or privacy right; or (iv) any claim that any of your Content caused damage to a third party. This defense and
indemnification obligation will survive the expiration or termination of this Agreement for any reason and your use of the SERVICE.<br/>
<strong>EXPORT CONTROL</strong>: SOSbeacon operates the SERVICE from its facilities in the United States of America and makes no representation that the
SERVICE is appropriate or will be available for use in other locations. If you use the SERVICE from outside the United States of America, you are
entirely responsible for compliance with applicable local laws, including but not limited to the export and import regulations of other countries in relation
to the SERVICE, your Content and any third party content.<br/>
<strong>GENERAL PROVISIONS</strong>: Enforcement of this Agreement will be governed by the laws of the State of California, USA, excluding its conflict and choice
of law principles. The exclusive jurisdiction and venue for any claims arising out of or related to this Agreement or your use of the SERVICE will lie in the
Superior Court of Alameda County in the State of California, or the United States District Court for the Northern District of California, and you irrevocably
agree to submit to the jurisdiction of such courts. The failure of SOSbeacon to enforce any right or provision in this Agreement will not constitute a waiver
of such right or provision unless acknowledged and agreed to by SOSbeacon in writing. In the event that a court of competent jurisdiction finds any
provision of this agreement to be illegal, invalid or unenforceable, the remaining portions will remain in full force and effect. This Agreement, and any
rights and licenses granted hereunder, may not be transferred or assigned by you, but may be assigned in whole or in part by SOSbeacon without
restriction.	
</div>
</div>
