<script language="javascript">
function submitForm() {
	var name = document.getElementById('txtName').value;
	var number = document.getElementById('txtNumber').value;
	if(name == '' || name == ' ') {
		alert("Name field canot be null!");
	} 
	else if(number == '' || number == ' ') {
		alert("Number field canot be null!");
	} 
	else {
		document.frm.submit();
	}
}
</script>

<div class="phone-list">
<div class="div1-1">
	<form name="frm" action="/web/phone/add" method="post">
	
	<h2>Add new phone</h2>
	
	<table class="tblEdit">
		<tr>
			<td>Phone name : </td>
			<td><input class="txt" type="text" name="txtName" id="txtName"/> <font color="red">*</font></td>
		</tr>
		<tr>
			<td>Phone number : </td>
			<td><input class="txt" type="text" name="txtNumber" id="txtNumber"/> <font color="red">*</font></td>
		</tr>
		<tr>
			<td>Phone type : </td>
			<td>
				<select name="txtType" class="sl">
					<option value="1">Iphone</option>
					<option value="2">Android</option>
					<option value="0">Unknown</option>
				</select>
			</td>
		</tr>
		<tr>
			<td>Phone imei : </td>
			<td><input class="txt" type="text" name="txtImei" id=""/></td>
		</tr>
		<tr>
			<td></td>
			<td class="tdButton">
				<a href="#" onclick="submitForm();">Add</a>
				<a href="/web/phone/list/">Cancel</a>
			</td>
		</tr>
		<?php if(isset($this->message)) :?>
		<tr>
			<td></td>
			<td colspan="2" class="tdMessage">
				<?php echo $this->message; ?>
			</td>
		</tr>
		<?php endif; ?>
	</table>
	</form>
</div>
</div>