<div class="message"><?php echo $this->message ?></div>
<form method="post" action="" class="account-form">
    <div class="select-phone"><?php echo $this->selectPhone ?></div>
    <div class="padding">
        <label>Phone number</label>
        <input type="text" name="number" class="text"/>
        <label>Password</label>
        <input type="password" name="password" class="text"/>
        <input type="submit" class="action bt-medium bt-green bt-login" value="Login"/>
    </div>
</form>