 <div id="ContainerFooter">
                <div class="footer_top">       
                    <div class="footer_top_center">
                        <div class="footer-title">SOSbeacon leverages the safety in numbers</div>
                        <div class="footer-copyright">Copyright &copy; 2010 - <?= date('Y');?> SOSbeacon. All Rights Reserved - 
                        <a href="http://www.sosbeacon.org/web/about/terms" target="_blank">Terms of service</a> - 
                        <a href="http://www.sosbeacon.org/web/about/privacy" target="_blank">Privacy</a>

                        </div>
                        <div class="footer-derverloped-by">Back Office Developed by SoftWeb Studios.</div>
                    </div>
                </div>
                <div class="footer_bot">
                    <div class="footer_bot_left">&nbsp;</div>
                        <div class="footer_bot_center">&nbsp;</div>
                        <div class="footer_bot_right">&nbsp;</div>

                    </div>     
                    <div class="clearFloat"></div>     
                </div>  
           <!-- /Container Footer -->