<style type="text/css">
    table hr {
        border: none;
        border-top: 1px dashed #999;
    }
</style>
<?php if (count($this->responseMessages)) : ?>
    <table style="border:1px solid #607298;width: 100%; max-width:600px">
        <thead>
            <tr>
                <th colspan="2" style="background: #607298; color: #fff; height: 30px;line-height: 30px; text-align: center;font-size: 20px;">Responder messages</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach($this->responseMessages as $n) :?>
                <tr>
                    <tr style="font-weight: bold; color: #3C4F7A;">
                        <td style="padding: 3px 6px;"><?php echo $n->getFrom(); ?></td>
                        <td style="padding: 3px 6px; text-align: right;width: 150px;font-weight: normal"><?php echo $n->getCreatedDate() ?> GMT</td>
                    </tr>
                    <td colspan="2" style="border:1px solid #f3f3f3; padding: 5px 6px;">
                        <?php echo htmlspecialchars($n->getMessage()) ?>
                    </td>
                </tr>
                <?php endforeach;?>
        </tbody>
    </table>
    <br /><br /><br />
<?php endif ?>

  
<?php if (count($this->responders)) : ?>
    <table style="border:1px solid #607298;width: 100%; max-width:600px">
        <thead>
            <tr>
                <th colspan="3" style="background: #607298; color: #fff; height: 30px;line-height: 30px; text-align: center;font-size: 20px;">Responder list</th>
            </tr>
            <tr style="background: #ECEFF5; color: #3C4F7A;"><th style="padding: 6px;">Responders</th><th style="padding: 6px;"># visits</th><th style="padding: 6px;"># messages</th></tr>
        </thead>
        <tbody>
            <?php foreach($this->responders as $receiver) :?>
                <tr>
                    <td style="padding: 3px 6px;border-bottom:1px solid #f3f3f3;" >
                        <strong><?php 
                        $receiveName = ($receiver->getName() ? $receiver->getName() : $receiver->getNumber());
                        echo htmlspecialchars($receiveName) ?></strong>
                        <br />
                        <?php echo $receiver->getNumber() ?>
                        <?php echo $receiver->getEmail() ?>
                    </td>
                    <td style="text-align: center;padding: 3px 6px;border-bottom:1px solid #f3f3f3;"><?php echo $receiver->getOpenLink() ?></td>
                    <td style="text-align: center;padding: 3px 6px;border-bottom:1px solid #f3f3f3;"><?php echo $receiver->getResponseChat() ?></td>
                </tr>
                <?php endforeach;?>
        </tbody>
    </table>
    <br /><br /><br />
<?php endif ?>
    
    
<?php if (count($this->noResponse)) : ?>
    <table style="border:1px solid #607298;width: 100%; max-width:600px">
        <thead>
            <tr>
                <th style="background: #607298; color: #fff; height: 30px;line-height: 30px; text-align: center;font-size: 20px;">No responder list</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach($this->noResponse as $nr) :?>
                <tr>
                    <td style="padding: 3px 6px;border-bottom:1px solid #f3f3f3;">
                        <strong><?php 
                        $receiveName = ($nr->getName() ? $nr->getName() : $nr->getNumber());
                        echo htmlspecialchars($receiveName) ?></strong>
                        <br />
                        <?php echo $nr->getNumber() ?>
                        <?php echo $nr->getEmail() ?>
                    </td>
                </tr>
                <?php endforeach;?>
        </tbody>
    </table>
    <br /><br /><br />
<?php endif ?>    
                
<?php if (count($this->alertlogRows)) : ?>
    <table style="border:1px solid #607298;width: 100%; max-width:600px">
        <thead>
            <tr>
                <th colspan="2" style="background: #607298; color: #fff; height: 30px;line-height: 30px; text-align: center;font-size: 20px;">Alert Messages</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach($this->alertlogRows as $item) :?>
                <tr>
                    <td colspan="2" style="background: #ECEFF5;font-weight: bold; color: #3C4F7A; padding: 6px;">Details</td>
                </tr>
                <tr>
                    <td style="border:1px solid #f3f3f3; padding: 3px 6px; width: 100px">From: </td>
                    <td style="border:1px solid #f3f3f3; padding: 3px 6px;"><?php echo htmlspecialchars($this->name) ?></td>
                </tr>
                <tr>
                    <td style="border:1px solid #f3f3f3; padding: 3px 6px">Number: </td>
                    <td style="border:1px solid #f3f3f3; padding: 3px 6px"><?php echo htmlspecialchars($this->number) ?></td>
                </tr>
                <tr>
                    <td style="border:1px solid #f3f3f3; padding: 3px 6px">Email: </td>
                    <td style="border:1px solid #f3f3f3; padding: 3px 6px"><?php echo htmlspecialchars($this->email) ?></td>
                </tr>
                <tr>
                    <td style="border:1px solid #f3f3f3; padding: 3px 6px;">Time: </td>
                    <td style="border:1px solid #f3f3f3; padding: 3px 6px;"><?php echo $item->updated_date ?> GMT</td>
                </tr>
                <tr>
                    <td style="border:1px solid #f3f3f3; padding: 3px 6px;" colspan="2"><?php echo $item->message ?></td>
                </tr>
            <?php endforeach;?>
        </tbody>
    </table>
<?php endif ?>