<script type="text/javascript"    src="http://maps.google.com/maps/api/js?sensor=false"></script>
<script type="text/javascript"   src="/scripts/lightbox.js"></script>
<!-- script type="text/javascript" src="/scripts/jwplayer/jwplayer.js"></script -->

<link rel="stylesheet" href="/styles/lightbox.css" type="text/css" />

<script src="/scripts/AudioJS/audio.js" type="text/javascript" charset="utf-8"></script>
<link rel="stylesheet" href="/scripts/AudioJS/audio-js.css" type="text/css" media="all" title="Audio JS" charset="utf-8">

<script type="text/javascript">
function loadLocation() {
	var alertloggroupId = $('#hdAlertloggroupId').val();
	var url = '/web/alert/location?alertId='+ alertloggroupId; 
	$('div.location').load(url);
}
function initialize(el, la,lo) {

      //var latlng2 = new google.maps.LatLng(21.040994081750677, 105.78739643096924);
      var latlng = new google.maps.LatLng(la, lo);
      var myOptions = {
      zoom: 12,
      center: latlng,
      mapTypeId: google.maps.MapTypeId.ROADMAP
    };

    var map = new google.maps.Map(el, myOptions);

    var marker = new google.maps.Marker({
        position: latlng,
        title:"My location"
    });
    marker.setMap(map);
}
//Load ajax
$(document).ready(function(){
        $('.google_map_canvas').each(function() {
            var la = $(this).attr("la");
            var lo = $(this).attr("lo");
            if((la != null && lo != null) && (la != 0 && lo != 0) && la != '' && lo != '') { 
                initialize(this, la, lo); 
            } else {
                $(this).parent('.gmap').html('NO LOCATION DATA');
            }
        });
});
var lastPlayer;
window.onload = function(){
    AudioJS.setup();
}
</script>
<?php 
$audioNum = 0 ; //Number of audio row
$totalAudio = 0;
?>
<?php if(isset($this->alertloggroupId)) : ?>
<div class="alert-list">
    <div class="col-left">
	<div class="title">&nbsp;</div>
	<input type="hidden" id="hdAlertloggroupId" value="<?php if(isset($this->alertloggroupId)) echo $this->alertloggroupId?>" />
		<?php if(isset($this->alertlogRows) && count($this->alertlogRows) >0) : ?>
			<?php endif; ?>
        <div class="alert">
            <?php if(isset($this->alertDataRows)) :
                $maps = $this->maps;
                $count = 0;
            ?>
            <?php 
                foreach ($this->alertDataRows as $key => $rows) {
                    foreach ($rows as $row) {
                        if($row->type != 0) $totalAudio++;
                    }
                }
            ?>
            <?php foreach($this->alertDataRows as $key => $rows): ?>
		<div class="alert-rows">
         <?php
         if (array_key_exists($count, $this->alertlogRows)) {
           $alogRow = $this->alertlogRows[$count];
           $count ++ ; ////#### edit
           ?>
            <div class="details">
            <div class="details-title">Details</div>
                <div>
                <table cellpadding="0" cellspacing="0">
                    <tr>
                        <td>From:</td>
                        <td>
                        <?php echo htmlspecialchars($this->phoneRows->getName()); ?>
                        </td>
                    </tr>
                    <tr>
                        <td>Number:</td>
                        <td><?php if(isset($this->phoneRows)) echo $this->phoneRows->getNumber() ?></td>
                    </tr>
                    <tr>
                        <td>Email:</td>
                        <td>
                        <?php echo htmlspecialchars($this->phoneRows->getEmail()) ?>
                        </td>
                    </tr>
                    <tr>
                        <td>Time:    </td>
                        <td><?php echo $alogRow->updated_date ?> GMT</td>
                    </tr>
                    <tr>
                        <td>Latitude:    </td>
                        <td><?php echo $alogRow->latitude ?></td>
                    </tr>
                    <tr>
                        <td>Longitude:  </td>
                        <td><?php echo $alogRow->longtitude ?></td>
                    </tr>
                    <tr>
                        <td>Text:     </td>
                        <td><?php echo $alogRow->message ?></td>
                    </tr>
                </table>
                </div>
</div>
        <?php } ?>
<?php
if (array_key_exists($key, $maps)) :
    $map = $maps[$key];
?>
    <div class="gmap">
        <div class="google_map_canvas" la="<?php echo $map['latitude'] ?>" lo="<?php echo $map['longtitude'] ?>"></div>
        <div class="date">Created Date: <?php echo $map['updated_date']." GMT" ; ?></div>
    </div>
<?php endif; ?>
<div class="main-photo">
	<?php foreach ($rows as $row) :?>
	<?php if($row->type != null && $row->type == 0) :  //image ?>
	<div class="photo-block">
		<div class="photo">
			<a href="<?php echo $row->path ?>" rel="lightbox[flowers]" title="Photo by SOSbeacon">
				<img src="<?php echo $row->path ; ?>"/>
			</a>	
		</div>
		<div class="date">Created Date: <?php echo $row->created_date." GMT" ; ?></div>
	</div>
	<?php endif; ?>  
	<?php endforeach;?>  
 </div>
 <div class="main-audio">
 <?php foreach ($rows as $row) :?>
 <?php if($row->type != 0) : //media ?>  
 	<?php $audioNum++ //Up value Number of audio row to 1?>
        <div class="media" data="<?php echo $row->path; ?>"><div id="media-<?php echo $audioNum ?>"></div></div>
        
        <!-- audio id="audio-<?php echo $audioNum ?>" src="<?php echo Sos_Service_Functions::$appUrl . $row->path; ?>" width="420" height="65"></audio>
        <script type="text/javascript">
            lastPlayer = jwplayer("audio-<?php echo $audioNum ?>").setup({
                flashplayer: "/scripts/jwplayer/player.swf",
                controlbar: { position : "bottom" },
                backcolor : "#ffffff",
                lightcolor : "#ffffff"
            });
        </script-->
        <div class="audio-js-box vim-css">
            <audio class="audio-js" controls preload <?php if ($totalAudio == $audioNum): ?>autoplay="autoplay"<?php endif; ?> >
                <source src="<?php echo Sos_Service_Functions::$appUrl . $row->path; ?>">
            </audio>
        </div>
        
	<div>Created Date: <?php echo $row->created_date." GMT" ; ?></div>
<?php endif; ?>    
<?php endforeach;?>
<!-- When iphone call Emergency, audio null -->
<?php $isIphoneCheckin = 0;?>
<?php foreach ($rows as $row) :?>					
	 <?php if($audioNum == 0 && $row->alertlogType == 1) { //IF Emergency
	 		$isIphoneCheckin = 1;
	 	}
	 ?>
<?php endforeach;?>	 
<?php if($isIphoneCheckin == 1) :?>
 	<div class="emergency-null">Emergency calls CAN NOT be recorded on iPhones due to Apple policy</div>
<?php endif;?>	
</div>
<!-- END OF MAIN-AUDIO -->
<div class="clearFloat"></div>
</div>
<?php endforeach;?>
<?php endif;?>
</div>
</div>
</div>
<?php else :?>
<div class="alert-list">
	<div class="div1">
		<br/><br/>
		Cannot found Review Phone History page with ID string: "<?php if(isset($this->token)) echo $this->token ?>"
	</div>
</div>
<?php endif; ?>
<script type="text/javascript">
$(document).ready(function() {
    <?php if ($audioNum > 0) :?>
        // lastPlayer.play();
    <?php endif; ?>
});
</script>
