   <!-- Container -->
    <div id="Container">
         <div id="ContainerInside">
           <div id="Content">
                <div class="main-content">

                       <div id='user-forgot'>
<div id="title">Title</div>



<div class="message">
	</div>

</div>                </div>               
           </div> 
          <? include($_CFG['fragmentsDir'].$_SESSION[culture].'/fragment_footer.inc');?>
         </div>   
     </div>
     <!-- /Container -->
     
     
