<head> 
    <meta name="viewport" content="width=device-width; initial-scale=1.0; maximum-scale=1.0; user-scalable=0;" />
    <meta name="apple-mobile-web-app-capable" content="yes" />
    <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent" />
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" /> 
    <link rel="icon" href="<?=$_CFG['rootURL']?>/images/logo.ico" type="image/x-icon" />
    <link rel="shortcut icon" href="<?=$_CFG['rootURL']?>/images/logo.ico" type="image/x-icon" />
    <title>SOSbeacon leverages the safety in numbers</title><link href="<?=$_CFG['rootURL']?>styles/style.css" media="screen" rel="stylesheet" type="text/css" >
<link href="<?=$_CFG['rootURL']?>styles/global.css" media="screen" rel="stylesheet" type="text/css" >

<link href="<?=$_CFG['rootURL']?>styles/superfish.css" media="screen" rel="stylesheet" type="text/css" >
<link href="<?=$_CFG['rootURL']?>styles/no-auth.css" media="screen" rel="stylesheet" type="text/css" >

<link type="text/css" href="<?=$_CFG['rootURL']?>css/smoothness/jquery-ui-1.8.16.custom.css" rel="Stylesheet" />	
<script type="text/javascript" src="<?=$_CFG['rootURL']?>js/jquery-1.6.2.min.js"></script>
<script type="text/javascript" src="<?=$_CFG['rootURL']?>js/jquery-ui-1.8.16.custom.min.js"></script>

</head>  